apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://thetogi.github.io/k8s-gitops-lab/helm-repo
    chart: sample-app
    targetRevision: 0.1.2
    helm:
      values: |
        image:
          repository: sample-app
          tag: "0.1.0"
          pullPolicy: IfNotPresent
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true